baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'My New Hugo Site'

# [[menus.main]]
# name = 'Home'
# pageRef = '/'
# weight = 10

# [[menus.main]]
# name = 'Posts'
# pageRef = '/posts'
# weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# [params]
#   banner = 'images/banner.png'
#   banner_srcset.enable = true

# [[params.banner_srcset.srcset]]
# src = "/images/banner-600w.webp"
# media = "(max-width: 479px)"

# [[params.banner_srcset.srcset]]
# src = "/images/banner-800w.webp"
# media = "(max-width: 799px)"

# [[params.banner_srcset.srcset]]
# src = "/images/banner.webp"
# media = "(min-width: 800px)"

