name = 'hugo-theme-reimu'
license = 'MIT'
licenselink = 'https://github.com/D-Sketon/hugo-theme-reimu/blob/main/LICENSE'
description = 'A Hakurei Reimu style Hugo theme'
homepage = 'https://github.com/D-Sketon/hugo-theme-reimu'
demosite = 'https://github.com/D-Sketon/hugo-theme-reimu'
min_version = "0.116.0"

tags = [
  'Blog',
  'Touhou',
  'Chinese',
  'Responsive',
  'Dark',
  'Light',
  'Customizable',
]
features = [
  'Blog',
  'Touhou',
  'Chinese',
  'Responsive',
  'Dark',
  'Light',
  'Customizable',
]

[author]
name = 'D-Sketon'
homepage = 'https://d-sketon.github.io/'
